### PR TITLE
Added CI Build 

### LINKED ISSUE #7: binary
can you publish compiled binary file for ESP32-DevKit1 or NodeMCU32 ...
(and some info what file / what channel to be used) ...

regards,
VALONI

### PR DESCRIPTION
**Pull request by saikek**
Added CI build using Github actions. 
Artifacts (firmware.bin) are available on the actions page. Closes #7 
Added Badge (Not sure if you'll need to update first page with your link or it will be done automatically).

### CODE REVIEW

**Comment by saikek** [comment]
I was not able to name artifact with Commit name, so for the moment it's just called `esp32-sigrok.bin`

**Comment by Ebiroll** [comment]
OK thanks, I just need to add some way to configure wifi over the serial
port. The wifi settings must be set before starting the build.

**Comment by saikek** [comment]
@Ebiroll - wellcome.
You can create ticket for configuration issues - maybe I can help with the configuration.

**Comment by Ebiroll** [comment]
OK, I did create the new Issue,
https://github.com/Ebiroll/esp32_sigrok/issues/10
I dont like the idea of having to download an app, that is why I suggested
the lagacy, console provisioning example.
I think a simplified version with input from the console would be better.

**Pull request merged**
